In [1]:
import numpy as np
import pandas as pd
#import preprocessing
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression

## Example dataframe

In [68]:
df = pd.read_csv('metals_daily_train.csv')
df = df.dropna(axis=0)
df.head(14)

,date,p0,p1,p2,f000_open,f000_high,f000_low,f000_settle,f001_open,f001_high,...,f136_open,f136_high,f136_low,f136_settle,f137_open,f137_high,f137_low,f137_settle,week,week_date
109,20081201,444.511058,457.032497,457.032497,53.08,56.33,52.62,56.29,49.11,52.15,...,9420.0,9680.0,9315.0,9540.0,9520.0,9800.0,9495.0,9650.0,2030,20081201
110,20081202,446.908899,465.530103,459.323035,55.99,56.29,54.68,55.30,51.80,52.24,...,9480.0,9600.0,9430.0,9510.0,9640.0,9730.0,9560.0,9630.0,2030,20081201
111,20081203,453.484820,482.060575,459.696940,56.50,56.72,54.65,55.21,53.01,53.02,...,9495.0,9580.0,9400.0,9500.0,9530.0,9690.0,9505.0,9590.0,2030,20081201
112,20081204,447.532919,472.395859,459.964389,55.50,57.81,54.88,57.62,51.75,54.42,...,9485.0,9485.0,9120.0,9145.0,9400.0,9445.0,9205.0,9225.0,2030,20081201
113,20081205,447.084228,471.922241,459.503235,58.50,60.00,56.63,56.75,54.70,56.18,...,8710.0,9000.0,8595.0,8665.0,8885.0,8940.0,8670.0,8715.0,2030,20081201
114,20081208,447.227191,472.073147,459.650169,55.03,55.85,54.14,54.67,51.82,53.77,...,8315.0,9010.0,8315.0,8900.0,8400.0,9060.0,8400.0,8970.0,2031,20081208
115,20081209,447.285703,472.134908,459.710306,55.25,55.65,54.17,55.38,53.34,53.82,...,9270.0,9300.0,8955.0,9135.0,9270.0,9375.0,9010.0,9170.0,2031,20081208
116,20081210,447.650117,472.519568,460.084842,55.16,55.60,53.78,54.44,53.36,53.71,...,9165.0,9400.0,9165.0,9295.0,9290.0,9460.0,9170.0,9355.0,2031,20081208
117,20081211,448.237028,473.139085,460.688056,54.86,55.32,52.60,55.32,53.45,53.60,...,9350.0,9350.0,9140.0,9205.0,9395.0,9395.0,9190.0,9270.0,2031,20081208
118,20081212,449.094065,467.806318,459.073933,55.85,56.50,54.22,54.46,53.92,54.50,...,9200.0,9215.0,8910.0,9090.0,9230.0,9230.0,8895.0,9070.0,2031,20081208
119,20081215,449.842555,468.585995,459.839056,54.95,56.52,54.66,54.84,53.00,53.52,...,9280.0,9350.0,9215.0,9270.0,9190.0,9330.0,9175.0,9270.0,2032,20081215
120,20081216,449.382661,474.348364,459.368942,54.50,54.50,52.17,52.25,52.69,52.69,...,9350.0,9350.0,9100.0,9195.0,9110.0,9260.0,9000.0,9130.0,2032,20081215
121,20081217,449.520530,493.223915,459.509875,52.62,53.80,51.33,52.07,50.72,51.08,...,9250.0,9395.0,9250.0,9315.0,9185.0,9360.0,9185.0,9275.0,2032,20081215
122,20081218,450.303392,494.082888,460.310134,52.12,52.15,49.58,50.31,50.05,50.55,...,9295.0,9375.0,9295.0,9325.0,9280.0,9330.0,9200.0,9255.0,2032,20081215

## Selection of the most correlated features

In [69]:
def top_correlated(df, nb_features, threshold, correlation_method=3):
    """Select top 20 correlated features from DataFrame"""
    # select settle prices only
    keep_col = [0, 2] + list(range(7, 557, 4))
    selected_columns = df.iloc[:, keep_col].columns
    
    # compute correlation matrix
    df_cor = pd.DataFrame(columns=['pearson', 'spearman', 'kendall'])
    df_cor['pearson'] = df[selected_columns].corr(method='pearson')['p1']
    df_cor['spearman'] = df[selected_columns].corr(method='spearman')['p1']
    df_cor['kendall'] = df[selected_columns].corr(method='kendall')['p1']
    df_cor['score'] = (abs(df_cor['pearson']) + abs(df_cor['spearman']) + abs(df_cor['kendall'])) / 3
    
    # sort depending on the correlation_method 
    col = df_cor.columns[correlation_method]
    df_cor_sorted = df_cor.sort_values(by=col, ascending=False)[col]    
    
    # retrieve the top nb_features correlated with p1
    selected_features = df_cor_sorted.index[:nb_features] 
    
    # eliminate features that are too correlated to each other
    df_cor_count = df_cor.loc[selected_features].copy()
    df_cor_count[df_cor_count < threshold] = 0
    df_cor_count[df_cor_count >= threshold] = 1
    df_cor_count = df_cor_count.sum(axis=1)
    df_cor_count = df_cor_count[df_cor_count > 0]
    df_cor_count = df_cor_count.sort_values(ascending=False)
    
    # keep 20 at most
    limit = min(20, len(df_cor_count))
    selected_features = df_cor_count.index[:limit]
    
    return selected_features

In [70]:
selected_features = top_correlated(df, 50, 0.75)
selected_features

Index(['p1', 'f091_settle', 'f029_settle', 'f090_settle', 'f131_settle',
       'f132_settle', 'f130_settle', 'f133_settle', 'f028_settle',
       'f135_settle', 'f134_settle', 'f011_settle', 'f010_settle',
       'f002_settle', 'f004_settle', 'f003_settle', 'f097_settle'],
      dtype='object')

In [71]:
selected_features = selected_features.insert(0, 'date')
selected_features

Index(['date', 'p1', 'f091_settle', 'f029_settle', 'f090_settle',
       'f131_settle', 'f132_settle', 'f130_settle', 'f133_settle',
       'f028_settle', 'f135_settle', 'f134_settle', 'f011_settle',
       'f010_settle', 'f002_settle', 'f004_settle', 'f003_settle',
       'f097_settle'],
      dtype='object')

## Reduction of dimension by PCA

In [72]:
def pca_selection(df, n=20):
    "Perform PCA to reduce then number of features"
    # first scale data
    X = df.values
    scaler = StandardScaler()
    X_sc = scaler.fit_transform(X)
    
    # PCA
    pca = PCA(n_components=n)
    X_pca = pca.fit_transform(X_sc)
    
    return pd.DataFrame(X_pca, index=df.index)

In [73]:
df_pca = pca_selection(df)
df_pca.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
109,-1.551894,32.879244,1.749189,1.961070,13.635106,8.942555,10.719506,7.749649,-3.093242,-0.339466,0.897852,1.780742,1.949166,0.825258,2.144379,-1.138141,-2.836098,0.064917,-3.091560,-2.622609
110,-2.504254,33.212287,1.425177,2.605029,13.200869,8.479536,10.016911,8.050657,-3.381756,0.115520,0.390680,1.317720,1.425833,0.692794,2.052838,-0.675521,-2.353417,0.028374,-2.956283,-2.177149
111,-3.258635,33.174910,1.251037,2.999204,13.010946,8.238106,9.759872,8.311804,-3.444505,0.100865,0.706402,1.354240,1.175834,0.295531,1.998934,-0.359776,-2.037846,0.014732,-2.885141,-1.992771
112,-4.128095,33.789522,0.739162,3.379791,12.946017,8.287326,10.349546,7.794329,-3.002137,0.403191,1.355227,1.370025,0.740066,0.043531,1.751358,-0.450043,-2.114068,-0.201339,-2.881336,-2.167757
113,-5.582836,35.118990,0.347171,3.950416,13.222885,8.327585,11.132295,6.996393,-2.502764,0.240236,1.748788,1.169872,0.469832,-0.038429,1.579192,-0.377466,-1.491764,-0.460097,-2.726936,-2.102085

## Reformatting the dataframe

In [74]:
def reformat_as_sequence(df, input_seq_len, output_seq_len):
    # columns of the reformatted dataframe
    cols= ['date_t']
    for i in range(input_seq_len-1, 0, -1):
        cols += ['p1_(t-{})'.format(i)]
    cols += ['p1_t']
    for i in range(1, output_seq_len+1):
        cols += ['p1_(t+{})'.format(i)]
    df_reformat = pd.DataFrame(columns=cols)
    
    # t will slide through the time series and create a row
    lim = len(df) - output_seq_len
    for t in range(input_seq_len, lim):
        row = [df['date'].iloc[t]] + list(df['p1'].iloc[t-input_seq_len:t+output_seq_len].values)
        df_reformat.loc[t] = row
    return df_reformat

In [75]:
df_ref = reformat_as_sequence(df, 20, 3)
df_ref.head()

,date_t,p1_(t-19),p1_(t-18),p1_(t-17),p1_(t-16),p1_(t-15),p1_(t-14),p1_(t-13),p1_(t-12),p1_(t-11),...,p1_(t-6),p1_(t-5),p1_(t-4),p1_(t-3),p1_(t-2),p1_(t-1),p1_t,p1_(t+1),p1_(t+2),p1_(t+3)
20,20090106.0,457.032497,465.530103,482.060575,472.395859,471.922241,472.073147,472.134908,472.519568,473.139085,...,494.082888,494.466420,499.496445,498.971557,505.969313,505.688433,519.860552,519.289737,518.833986,519.061761
21,20090107.0,465.530103,482.060575,472.395859,471.922241,472.073147,472.134908,472.519568,473.139085,467.806318,...,494.466420,499.496445,498.971557,505.969313,505.688433,519.860552,519.289737,518.833986,519.061761,518.970627
22,20090108.0,482.060575,472.395859,471.922241,472.073147,472.134908,472.519568,473.139085,467.806318,468.585995,...,499.496445,498.971557,505.969313,505.688433,519.860552,519.289737,518.833986,519.061761,518.970627,518.909889
23,20090109.0,472.395859,471.922241,472.073147,472.134908,472.519568,473.139085,467.806318,468.585995,474.348364,...,498.971557,505.969313,505.688433,519.860552,519.289737,518.833986,519.061761,518.970627,518.909889,518.826397
24,20090112.0,471.922241,472.073147,472.134908,472.519568,473.139085,467.806318,468.585995,474.348364,493.223915,...,505.969313,505.688433,519.860552,519.289737,518.833986,519.061761,518.970627,518.909889,518.826397,519.008596

## Adding instruments

#### trends

In [76]:
def indicator(x,bucket):
    if(bucket%2==0): #number of buckets have to be strictly odd
        return 0,0
    else:    
        dif=np.array(np.diff(x))     
        output=np.zeros(len(x))
        ratio=np.zeros(len(x))
    
        #used to calculate the ratio of change in value from yesterday's value     
        for i in range(1,len(x)): 
            ratio[i]=(100*dif[i-1]/x[i])
            
        #values have the percentile boundary values of the buckets.
        #eg: if bucket=3, values = [33 percentile , 66 percentile] value

        values=np.array(range(bucket-1))    
        for i in range(len(values)):
            values[i]=np.sort(ratio)[int(len(x)/bucket)*(i+1)-1]

        #buckets have the categorical value that needs to be filled.
        #eg: if bucket=3, buckets= [-1,0,1]

        start=-int((bucket-1)/2)
        buckets=np.array(range(bucket))        
        for i in range(len(buckets)):
            buckets[i]=start
            start+=1
            
        #This loop is used to assign the custom bucket values.
        #eg: if bucket =3, value -1 is assigned if the value is below 33 pecentile
        # value 0 for between 33 to 66 percentile
        #value 1 for above 66 percentile. 

        for i in range(len(ratio)): #used to assign values for 
            for j in range(len(values)):
                if (j==0):
                    if(ratio[i]<=values[j]):
                        output[i]=buckets[j]
                    else:
                        pass
                elif j==(len(values)-1):
                    if(ratio[i]>values[j]):
                        output[i]=buckets[j+1]
                    else:
                        pass
                elif (ratio[i]>values[j-1]) and (ratio[i]<values[j]):
                    output[i]=buckets[j]  

        return output


def indicator_panda(p,bucket):
    out=pd.DataFrame()
    for i in p.columns:
        out[i]=indicator(p[i].values,bucket)
    return out

In [77]:
def trend_bins(df, lag, block=None):
    """Return categories of trend (-1, 0, +1) over the last lag days at each date"""
    # compute slopes 
    slopes = []
    for t in range(lag, len(df)):
        linreg = LinearRegression()
        linreg.fit(np.arange(lag).reshape(-1, 1), df.iloc[(t-lag):t].values)
        slopes.append(list(linreg.coef_.flatten()))
    df_slopes = pd.DataFrame(slopes, columns=df.columns)
    
    # categorize slopes
    df_copy_slopes = df_slopes.copy()
    for col in df.columns:
        if col not in block:
            thre_low = np.quantile(df_copy_slopes[col].values, 0.33)
            thre_high = np.quantile(df_copy_slopes[col].values, 0.66)
            df_slopes[col] = 0
            df_slopes[col][df_copy_slopes[col] >= thre_high] = 1
            df_slopes[col][df_copy_slopes[col] <= thre_low] = -1
            
    df_slopes = df_slopes.drop(block, axis=1)
    for col in block:
        df_slopes[col] = df[col].values[lag:len(df)]
        
    return df_slopes

In [84]:
df_trends = trend_bins(df[selected_features], 20, block=['date'])
#df_trends = df_trends.rename(index=str, columns={'date' : 'date_t'})
df_trends = df_trends.set_index('date')
df_ref = df_ref.set_index('date_t')

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [86]:
# join
df_ref.join(df_trends, rsuffix='r')

,p1_(t-19),p1_(t-18),p1_(t-17),p1_(t-16),p1_(t-15),p1_(t-14),p1_(t-13),p1_(t-12),p1_(t-11),p1_(t-10),...,f133_settle,f028_settle,f135_settle,f134_settle,f011_settle,f010_settle,f002_settle,f004_settle,f003_settle,f097_settle
date_t,,,,,,,,,,,,,,,,,,,,,
20090106.0,457.032497,465.530103,482.060575,472.395859,471.922241,472.073147,472.134908,472.519568,473.139085,467.806318,...,-1,-1,1,0,1,1,1,1,1,1
20090107.0,465.530103,482.060575,472.395859,471.922241,472.073147,472.134908,472.519568,473.139085,467.806318,468.585995,...,-1,-1,1,1,1,1,1,1,1,1
20090108.0,482.060575,472.395859,471.922241,472.073147,472.134908,472.519568,473.139085,467.806318,468.585995,474.348364,...,0,-1,1,1,1,1,1,1,1,1
20090109.0,472.395859,471.922241,472.073147,472.134908,472.519568,473.139085,467.806318,468.585995,474.348364,493.223915,...,0,0,1,1,1,1,1,1,1,1
20090112.0,471.922241,472.073147,472.134908,472.519568,473.139085,467.806318,468.585995,474.348364,493.223915,494.082888,...,1,0,1,1,1,1,1,1,1,1
20090113.0,472.073147,472.134908,472.519568,473.139085,467.806318,468.585995,474.348364,493.223915,494.082888,494.466420,...,1,0,1,1,1,1,1,1,1,1
20090114.0,472.134908,472.519568,473.139085,467.806318,468.585995,474.348364,493.223915,494.082888,494.466420,499.496445,...,1,1,1,1,1,1,1,1,1,1
20090115.0,472.519568,473.139085,467.806318,468.585995,474.348364,493.223915,494.082888,494.466420,499.496445,498.971557,...,1,1,1,1,1,1,1,1,1,1
20090116.0,473.139085,467.806318,468.585995,474.348364,493.223915,494.082888,494.466420,499.496445,498.971557,505.969313,...,1,1,1,1,0,0,0,1,1,1
20090120.0,467.806318,468.585995,474.348364,493.223915,494.082888,494.466420,499.496445,498.971557,505.969313,505.688433,...,1,1,1,1,0,0,0,1,1,1
20090121.0,468.585995,474.348364,493.223915,494.082888,494.466420,499.496445,498.971557,505.969313,505.688433,519.860552,...,1,1,1,1,-1,-1,-1,1,1,1
20090122.0,474.348364,493.223915,494.082888,494.466420,499.496445,498.971557,505.969313,505.688433,519.860552,519.289737,...,1,1,1,1,-1,-1,-1,1,1,1
20090123.0,493.223915,494.082888,494.466420,499.496445,498.971557,505.969313,505.688433,519.860552,519.289737,518.833986,...,1,1,1,1,-1,-1,-1,1,1,0
20090202.0,494.082888,494.466420,499.496445,498.971557,505.969313,505.688433,519.860552,519.289737,518.833986,519.061761,...,1,1,1,1,-1,-1,-1,1,1,1
20090203.0,494.466420,499.496445,498.971557,505.969313,505.688433,519.860552,519.289737,518.833986,519.061761,518.970627,...,1,1,1,1,-1,-1,-1,1,1,1
20090204.0,499.496445,498.971557,505.969313,505.688433,519.860552,519.289737,518.833986,519.061761,518.970627,518.909889,...,1,1,1,1,-1,-1,-1,0,0,0
20090205.0,498.971557,505.969313,505.688433,519.860552,519.289737,518.833986,519.061761,518.970627,518.909889,518.826397,...,1,1,1,1,-1,-1,-1,-1,-1,0
20090206.0,505.969313,505.688433,519.860552,519.289737,518.833986,519.061761,518.970627,518.909889,518.826397,519.008596,...,1,0,1,1,-1,-1,-1,-1,-1,0
20090209.0,505.688433,519.860552,519.289737,518.833986,519.061761,518.970627,518.909889,518.826397,519.008596,518.947849,...,1,0,1,1,-1,-1,-1,-1,-1,0
20090210.0,519.860552,519.289737,518.833986,519.061761,518.970627,518.909889,518.826397,519.008596,518.947849,518.833986,...,0,0,1,1,-1,-1,-1,-1,-1,0
20090211.0,519.289737,518.833986,519.061761,518.970627,518.909889,518.826397,519.008596,518.947849,518.833986,518.833986,...,0,0,1,1,-1,-1,-1,-1,-1,0
20090212.0,518.833986,519.061761,518.970627,518.909889,518.826397,519.008596,518.947849,518.833986,518.833986,518.492698,...,0,0,1,1,-1,-1,-1,-1,-1,0
20090213.0,519.061761,518.970627,518.909889,518.826397,519.008596,518.947849,518.833986,518.833986,518.492698,518.591246,...,0,0,1,1,-1,-1,-1,-1,-1,0
20090217.0,518.970627,518.909889,518.826397,519.008596,518.947849,518.833986,518.833986,518.492698,518.591246,518.758106,...,1,0,1,1,0,0,-1,-1,-1,0
20090218.0,518.909889,518.826397,519.008596,518.947849,518.833986,518.833986,518.492698,518.591246,518.758106,525.200233,...,1,0,1,1,0,0,-1,-1,-1,0
20090219.0,518.826397,519.008596,518.947849,518.833986,518.833986,518.492698,518.591246,518.758106,525.200233,524.241488,...,1,0,1,1,0,0,0,-1,-1,-1
20090220.0,519.008596,518.947849,518.833986,518.833986,518.492698,518.591246,518.758106,525.200233,524.241488,524.777953,...,0,0,1,1,0,0,0,-1,-1,-1
20090223.0,518.947849,518.833986,518.833986,518.492698,518.591246,518.758106,525.200233,524.241488,524.777953,525.277084,...,0,0,1,1,0,0,0,-1,-1,-1
20090224.0,518.833986,518.833986,518.492698,518.591246,518.758106,525.200233,524.241488,524.777953,525.277084,525.123404,...,0,0,1,1,0,0,0,-1,-1,-1
20090226.0,518.833986,518.492698,518.591246,518.758106,525.200233,524.241488,524.777953,525.277084,525.123404,525.246340,...,0,0,0,0,0,0,0,-1,-1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20180327.0,581.831816,582.695300,582.935877,577.591761,574.487895,572.517472,570.547632,569.347628,557.668364,561.949504,...,-1,-1,-1,-1,0,0,0,0,0,0
20180328.0,582.695300,582.935877,577.591761,574.487895,572.517472,570.547632,569.347628,557.668364,561.949504,559.344893,...,-1,-1,-1,-1,0,0,0,0,0,0
20180329.0,582.935877,577.591761,574.487895,572.517472,570.547632,569.347628,557.668364,561.949504,559.344893,559.586876,...,-1,-1,-1,-1,0,0,-1,0,0,0
20180403.0,577.591761,574.487895,572.517472,570.547632,569.347628,557.668364,561.949504,559.344893,559.586876,562.553504,...,-1,-1,-1,-1,0,0,-1,0,0,-1
20180404.0,574.487895,572.517472,570.547632,569.347628,557.668364,561.949504,559.344893,559.586876,562.553504,558.645649,...,-1,-1,-1,-1,0,0,-1,0,0,-1
20180409.0,572.517472,570.547632,569.347628,557.668364,561.949504,559.344893,559.586876,562.553504,558.645649,557.902067,...,-1,-1,-1,-1,0,0,-1,0,0,-1
20180410.0,570.547632,569.347628,557.668364,561.949504,559.344893,559.586876,562.553504,558.645649,557.902067,553.349387,...,-1,-1,-1,-1,0,0,-1,0,0,-1
20180411.0,569.347628,557.668364,561.949504,559.344893,559.586876,562.553504,558.645649,557.902067,553.349387,550.052671,...,-1,-1,-1,-1,1,1,-1,0,0,-1
20180412.0,557.668364,561.949504,559.344893,559.586876,562.553504,558.645649,557.902067,553.349387,550.052671,553.041729,...,-1,-1,-1,-1,1,1,-1,0,0,0
20180413.0,561.949504,559.344893,559.586876,562.553504,558.645649,557.902067,553.349387,550.052671,553.041729,526.825979,...,-1,0,-1,-1,1,1,0,0,0,0
20180416.0,559.344893,559.586876,562.553504,558.645649,557.902067,553.349387,550.052671,553.041729,526.825979,520.757021,...,-1,0,-1,-1,1,1,0,0,0,0
20180417.0,559.586876,562.553504,558.645649,557.902067,553.349387,550.052671,553.041729,526.825979,520.757021,522.852892,...,-1,0,-1,-1,1,1,0,0,0,0
20180418.0,562.553504,558.645649,557.902067,553.349387,550.052671,553.041729,526.825979,520.757021,522.852892,527.764784,...,0,0,-1,-1,1,1,0,0,0,0
20180419.0,558.645649,557.902067,553.349387,550.052671,553.041729,526.825979,520.757021,522.852892,527.764784,527.224057,...,0,0,-1,-1,1,1,0,0,0,0
20180420.0,557.902067,553.349387,550.052671,553.041729,526.825979,520.757021,522.852892,527.764784,527.224057,533.229050,...,0,1,-1,-1,1,1,0,0,0,0
20180423.0,553.349387,550.052671,553.041729,526.825979,520.757021,522.852892,527.764784,527.224057,533.229050,531.081007,...,0,1,-1,-1,1,1,0,0,0,0
20180424.0,550.052671,553.041729,526.825979,520.757021,522.852892,527.764784,527.224057,533.229050,531.081007,531.228172,...,1,1,0,-1,1,1,0,0,0,0
20180425.0,553.041729,526.825979,520.757021,522.852892,527.764784,527.224057,533.229050,531.081007,531.228172,534.418543,...,1,1,0,0,1,1,0,0,0,0
20180426.0,526.825979,520.757021,522.852892,527.764784,527.224057,533.229050,531.081007,531.228172,534.418543,530.250022,...,1,1,0,0,0,0,0,0,0,0
20180427.0,520.757021,522.852892,527.764784,527.224057,533.229050,531.081007,531.228172,534.418543,530.250022,537.910519,...,1,1,0,0,0,0,0,0,0,0
20180502.0,522.852892,527.764784,527.224057,533.229050,531.081007,531.228172,534.418543,530.250022,537.910519,536.752898,...,1,1,0,0,0,0,0,0,0,0
20180503.0,527.764784,527.224057,533.229050,531.081007,531.228172,534.418543,530.250022,537.910519,536.752898,537.236600,...,1,0,0,0,0,0,-1,-1,-1,0
20180504.0,527.224057,533.229050,531.081007,531.228172,534.418543,530.250022,537.910519,536.752898,537.236600,541.591698,...,1,0,0,0,0,0,-1,-1,-1,0
20180507.0,533.229050,531.081007,531.228172,534.418543,530.250022,537.910519,536.752898,537.236600,541.591698,546.406401,...,0,0,0,0,-1,-1,-1,-1,-1,0
20180508.0,531.081007,531.228172,534.418543,530.250022,537.910519,536.752898,537.236600,541.591698,546.406401,545.001743,...,0,0,0,0,-1,-1,-1,-1,0,0
20180509.0,531.228172,534.418543,530.250022,537.910519,536.752898,537.236600,541.591698,546.406401,545.001743,544.914770,...,0,0,0,0,-1,-1,-1,-1,0,0
20180510.0,534.418543,530.250022,537.910519,536.752898,537.236600,541.591698,546.406401,545.001743,544.914770,557.269121,...,0,0,0,0,-1,-1,-1,-1,0,0
20180511.0,530.250022,537.910519,536.752898,537.236600,541.591698,546.406401,545.001743,544.914770,557.269121,558.324518,...,0,0,0,0,-1,-1,-1,0,0,-1
20180514.0,537.910519,536.752898,537.236600,541.591698,546.406401,545.001743,544.914770,557.269121,558.324518,556.362398,...,0,0,0,0,-1,-1,-1,0,0,-1
20180515.0,536.752898,537.236600,541.591698,546.406401,545.001743,544.914770,557.269121,558.324518,556.362398,557.094841,...,0,0,0,0,-1,-1,-1,0,0,-1

## Train Test Split

In [ ]:
#from sklearn.model_selection import train_test_split #to adapt 
#train_df,test_df=train_test_split(dataframe, test_size=n)